### ISSUE TITLE
Method subMinutes does not exist.

### ISSUE THREAD

**Issue by willouch** [bennothommo/october-plugin-url-normaliser#5]
updating to new version return Method subMinutes does not exist.

thks

**Comment by bennothommo** [comment]
@willouch Thanks for the report, but that error must be coming from somewhere else. There's no `subMinutes` method used in this plugin.

**Comment by Marciobds** [comment]
Hi,

I had the same problem. The only update on October was in this plugin and after update the CMS crashes.

![image](https://user-images.githubusercontent.com/5437204/76517401-04d36680-643c-11ea-98df-21c797e3cabf.png)

![image](https://user-images.githubusercontent.com/5437204/76517432-11f05580-643c-11ea-8cc1-1cab7f38ad34.png)

Once I remove the plugin everything works fine.

The method  subMinutes is part of Carbon, which is on vendor folder of the plugin.

This seems be an incompatibility between Carbon and Laravel.

**Comment by bennothommo** [comment]
@Marciobds @willouch It appears it might be a conflict due to the fact I had added a certain build of October CMS as a dependency in Composer. This in turn was then included in the update from the marketplace. I have released version 1.1.5 which should hopefully resolve that. Would you mind upgrading and letting me know if that resolves the issue?

**Comment by Marciobds** [comment]
Hi,

I have reinstalled the plugin, seems to be working.

Thank you @bennothommo  :)

**Comment by willouch** [comment]
Hi,
Working now!
Resolved issue!!!

Thank you @bennothommo :)
